# Generated by Django 3.0.7 on 2020-06-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1', models.CharField(max_length=30)),
                ('team_2', models.CharField(max_length=30)),
                ('highlight_video_link', models.CharField(max_length=50)),
                ('highlight_video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
