# Generated by Django 3.0.8 on 2020-07-15 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0002_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='season',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
