# Generated by Django 3.0.8 on 2020-07-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0003_auto_20200715_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ids', models.CharField(max_length=200)),
                ('thumbnail', models.URLField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esports.Competition')),
            ],
        ),
    ]
