# Generated by Django 3.0.8 on 2020-07-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0004_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
