# Generated by Django 3.0.8 on 2020-07-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0005_highlight_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date_published',
            field=models.DateTimeField(null=True),
        ),
    ]
