# Generated by Django 3.1 on 2020-08-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0007_highlight_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='esports/images')),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Highlight',
        ),
    ]
