# Generated by Django 3.1 on 2020-08-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0008_auto_20200811_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='league',
            field=models.CharField(choices=[('SWC', 'Smite World Championship'), ('SPL', 'Smite Pro League'), ('SCC', 'Smite Challenger Circuit'), ('SOC', 'Smite Open Circuit')], default='SPL', max_length=3),
        ),
    ]
