# Generated by Django 3.1 on 2020-08-16 20:22

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0009_auto_20200811_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('competition_include_filters', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('competition_exclude_filters', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('match_include_filters', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('match_exclude_filters', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='ids',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=25), size=None),
        ),
        migrations.AlterField(
            model_name='competition',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esports.league'),
        ),
    ]
