# Generated by Django 3.1 on 2020-08-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0010_auto_20200816_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_logo',
            field=models.ImageField(null=True, upload_to='esports/images/league'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='esports/images/image'),
        ),
    ]
